### ISSUE TITLE
Somehow outdated/setup/install error

### ISSUE THREAD

**Issue by rugk** [OSM-Interrail-Planner/osm_interrail_planner#39]
```
$ conda env create --file rail_planner.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libwebp-base==1.2.0=h8ffe710_0
  - intel-openmp==2020.3=h57928b3_311
  - cffi==1.14.5=py39h0878f49_0
  - markupsafe==1.1.1=py39hb82d6ee_3
  - pixman==0.40.0=h8ffe710_0
  - zstd==1.4.9=h6255e5f_0
  - libssh2==1.9.0=hb06d900_5
  - icu==68.1=h0e60522_0
  - freexl==1.0.5=hd288d7e_1002
  - setuptools==49.6.0=py39hcbf5309_3
  - fontconfig==2.13.1=h1989441_1004
  - rtree==0.9.7=py39h09fdee3_1
  - curl==7.71.1=h4b64cdc_8
  - boost-cpp==1.74.0=h54f0996_2
  - m2w64-gmp==6.1.0=2
  - sqlite==3.34.0=h8ffe710_0
  - vc==14.2=hb210afc_4
  - libtiff==4.2.0=hc10be44_0
  - pyproj==3.0.1=py39h41cdc1e_0
  - jpeg==9d=h8ffe710_0
  - tk==8.6.10=h8ffe710_1
  - libspatialindex==1.9.3=h39d44d4_3
  - proj==7.2.0=h1cfcee9_2
  - pygeos==0.9=py39h6d74692_3
  - m2w64-libwinpthread-git==5.0.0.4634.697f757=2
  - lz4-c==1.9.3=h8ffe710_0
  - libpq==13.1=h4f54205_2
  - cairo==1.16.0=hba8bd2f_1007
  - m2w64-gcc-libs-core==5.3.0=7
  - libnetcdf==4.7.4=nompi_h3a9aa94_107
  - krb5==1.17.2=hbae68bd_0
  - libglib==2.66.7=h1e62bf3_1
  - libpng==1.6.37=h1d00b33_2
  - libkml==1.3.0=h02ac0ef_1012
  - win_inet_pton==1.1.0=py39hcbf5309_2
  - xz==5.2.5=h62dcd97_1
  - hdf5==1.10.6=nompi_h5268f04_1114
  - xerces-c==3.2.3=h0e60522_2
  - certifi==2020.12.5=py39hcbf5309_1
  - poppler==0.89.0=h3772339_5
  - vs2015_runtime==14.28.29325=h5e1d092_4
  - libxml2==2.9.10=hf5bbc77_3
  - m2w64-gcc-libgfortran==5.3.0=6
  - bzip2==1.0.8=h8ffe710_4
  - pcre==8.44=ha925a31_0
  - libspatialite==5.0.1=h6966176_2
  - wincertstore==0.2=py39hcbf5309_1006
  - cfitsio==3.470=h0af3d06_7
  - kealib==1.4.14=h0883a5c_1
  - m2w64-gcc-libs==5.3.0=7
  - openssl==1.1.1j=h8ffe710_0
  - libgdal==3.2.1=hd376e63_5
  - expat==2.2.10=h39d44d4_0
  - shapely==1.7.1=py39hc5aab28_2
  - fiona==1.8.18=py39h9f1b043_1
  - libffi==3.3=h0e60522_2
  - pandas==1.2.3=py39h2e25243_0
  - pysocks==1.7.1=py39hcbf5309_3
  - postgresql==13.1=h0f1a9bc_2
  - ca-certificates==2020.12.5=h5b45459_0
  - zlib==1.2.11=h62dcd97_1010
  - python==3.9.2=h7840368_0_cpython
  - numpy==1.20.1=py39h6635163_0
  - openjpeg==2.4.0=h48faf41_0
  - scipy==1.6.0=py39hc0c34ad_0
  - cryptography==3.4.4=py39h7bc7c5c_0
  - hdf4==4.2.13=h0e5069d_1004
  - gdal==3.2.1=py39h6795fcd_5
  - librttopo==1.1.0=ha743252_5
  - libcurl==7.71.1=h4b64cdc_8
  - libiconv==1.16=he774522_0
  - geos==3.9.0=h39d44d4_0
  - brotlipy==0.7.0=py39hb82d6ee_1001
  - tiledb==2.2.4=hddc2a84_1
  - freetype==2.10.4=h546665d_1
  - mkl==2020.4=hb70f87d_311
  - geotiff==1.6.0=hee96dd5_4
  - chardet==4.0.0=py39hcbf5309_1
  - gettext==0.19.8.1=h1a89ca6_1005
  - msys2-conda-epoch==20160418=1


$ python server.py                        
/var/home/rugk/Software/osm_interrail_planner/mytest/lib/python3.11/site-packages/geopandas/_compat.py:123: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/var/home/rugk/Software/osm_interrail_planner/server.py:2: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas as gpd
 * Serving Flask app 'server'
 * Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [14/Feb/2023 00:04:54] "HEAD / HTTP/1.1" 200 -
gio: http://127.0.0.1:5000/: Failed to find default application for content type ‘text/html’
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 1394, in run
    self.function(*self.args, **self.kwargs)
TypeError: 'bool' object is not callable
```

**Comment by rugk** [comment]
Also tried the manual way:
```
$ virtualenv -p python3 mytest                 
created virtual environment CPython3.11.1.final.0-64 in 389ms
  creator CPython3Posix(dest=/var/home/rugk/Software/osm_interrail_planner/mytest, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/var/home/rugk/.local/share/virtualenv)
    added seed packages: pip==23.0, setuptools==67.1.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

$ source mytest/bin/activate
$ pip install geopandas requests geojson osm2geojson ortools networkx momepy folium flask                  
Collecting geopandas
  Downloading geopandas-0.12.2-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 959.4 kB/s eta 0:00:00
Collecting requests
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 876.6 kB/s eta 0:00:00
Collecting geojson
  Downloading geojson-2.5.0-py2.py3-none-any.whl (14 kB)
Collecting osm2geojson
  Downloading osm2geojson-0.2.3.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting ortools
  Downloading ortools-9.5.2237-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 1.1 MB/s eta 0:00:00
Collecting networkx
  Downloading networkx-3.0-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 1.0 MB/s eta 0:00:00
Collecting momepy
  Downloading momepy-0.5.4-py3-none-any.whl (243 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.7/243.7 kB 1.3 MB/s eta 0:00:00
Collecting folium
  Downloading folium-0.14.0-py2.py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.3/102.3 kB 1.6 MB/s eta 0:00:00
Collecting flask
  Downloading Flask-2.2.2-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.5/101.5 kB 1.2 MB/s eta 0:00:00
Collecting pandas>=1.0.0
  Downloading pandas-1.5.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 1.0 MB/s eta 0:00:00
Collecting shapely>=1.7
  Downloading shapely-2.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 1.0 MB/s eta 0:00:00
Collecting fiona>=1.8
  Downloading Fiona-1.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 1.1 MB/s eta 0:00:00
Collecting pyproj>=2.6.1.post1
  Downloading pyproj-3.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 1.1 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-23.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 2.1 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (196 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.8/196.8 kB 992.0 kB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 14.1 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 1.8 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 1.4 MB/s eta 0:00:00
Collecting absl-py>=0.13
  Downloading absl_py-1.4.0-py3-none-any.whl (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 1.6 MB/s eta 0:00:00
Collecting numpy>=1.13.3
  Downloading numpy-1.24.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 949.0 kB/s eta 0:00:00
Collecting protobuf>=4.21.5
  Downloading protobuf-4.21.12-cp37-abi3-manylinux2014_x86_64.whl (409 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.8/409.8 kB 981.5 kB/s eta 0:00:00
Collecting libpysal>=4.2.0
  Downloading libpysal-4.7.0-py3-none-any.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 1.2 MB/s eta 0:00:00
Collecting tqdm>=4.27.0
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 1.2 MB/s eta 0:00:00
Collecting pygeos
  Downloading pygeos-0.14-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 868.0 kB/s eta 0:00:00
Collecting branca>=0.6.0
  Downloading branca-0.6.0-py3-none-any.whl (24 kB)
Collecting jinja2>=2.9
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 1.7 MB/s eta 0:00:00
Collecting Werkzeug>=2.2.2
  Downloading Werkzeug-2.2.2-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.7/232.7 kB 1.1 MB/s eta 0:00:00
Collecting itsdangerous>=2.0
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=8.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 1.2 MB/s eta 0:00:00
Collecting attrs>=19.2.0
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 10.3 MB/s eta 0:00:00
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Collecting munch>=2.3.2
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: setuptools in ./mytest/lib/python3.11/site-packages (from fiona>=1.8->geopandas) (67.1.0)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27 kB)
Collecting platformdirs
  Using cached platformdirs-3.0.0-py3-none-any.whl (14 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.11.2-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.8 MB/s eta 0:00:00
Collecting scipy>=0.11
  Downloading scipy-1.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.1/34.1 MB 1.1 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.1
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 1.1 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 kB 1.2 MB/s eta 0:00:00
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Building wheels for collected packages: osm2geojson
  Building wheel for osm2geojson (setup.py) ... done
  Created wheel for osm2geojson: filename=osm2geojson-0.2.3-py3-none-any.whl size=12706 sha256=c733bcc69d7c2061a5e7bb414800f9bc0de6915af929564a88081253d950cd74
  Stored in directory: /var/home/rugk/.cache/pip/wheels/9b/df/57/1b70c2ea461a8f5cb0e5aa0d516bda357e6416722e51192904
Successfully built osm2geojson
Installing collected packages: pytz, geojson, charset-normalizer, urllib3, tqdm, soupsieve, six, protobuf, platformdirs, packaging, numpy, networkx, MarkupSafe, itsdangerous, idna, click, certifi, attrs, absl-py, Werkzeug, shapely, scipy, requests, python-dateutil, pyproj, pygeos, ortools, munch, jinja2, cligj, click-plugins, beautifulsoup4, pandas, osm2geojson, flask, fiona, branca, libpysal, geopandas, folium, momepy
Successfully installed MarkupSafe-2.1.2 Werkzeug-2.2.2 absl-py-1.4.0 attrs-22.2.0 beautifulsoup4-4.11.2 branca-0.6.0 certifi-2022.12.7 charset-normalizer-3.0.1 click-8.1.3 click-plugins-1.1.1 cligj-0.7.2 fiona-1.9.1 flask-2.2.2 folium-0.14.0 geojson-2.5.0 geopandas-0.12.2 idna-3.4 itsdangerous-2.1.2 jinja2-3.1.2 libpysal-4.7.0 momepy-0.5.4 munch-2.5.0 networkx-3.0 numpy-1.24.2 ortools-9.5.2237 osm2geojson-0.2.3 packaging-23.0 pandas-1.5.3 platformdirs-3.0.0 protobuf-4.21.12 pygeos-0.14 pyproj-3.4.1 python-dateutil-2.8.2 pytz-2022.7.1 requests-2.28.2 scipy-1.10.0 shapely-2.0.1 six-1.16.0 soupsieve-2.3.2.post1 tqdm-4.64.1 urllib3-1.26.14

$ python server.py
/var/home/rugk/Software/osm_interrail_planner/mytest/lib/python3.11/site-packages/geopandas/_compat.py:123: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/var/home/rugk/Software/osm_interrail_planner/server.py:2: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas as gpd
 * Serving Flask app 'server'
 * Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [14/Feb/2023 00:00:47] "HEAD / HTTP/1.1" 200 -
gio: http://127.0.0.1:5000/: Failed to find default application for content type ‘text/html’
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 1394, in run
    self.function(*self.args, **self.kwargs)
TypeError: 'bool' object is not callable
```
